Vagrant.configure("2") do |config|

  config.vm.define "haproxyServer" do |haproxyServer|
    haproxyServer.vm.box = "bento/ubuntu-18.04"
    haproxyServer.vm.hostname = "haproxyServer"
    haproxyServer.vm.network :private_network, ip: "192.168.100.7"
    haproxyServer.vm.network "forwarded_port", guest: 80, host: 3000
    haproxyServer.vm.provision "shell", path: "haproxy.sh"

  end

  
  config.vm.define "web1" do |web1|
    web1.vm.box = "bento/ubuntu-18.04"
    web1.vm.hostname = "web1"
    web1.vm.network :private_network, ip: "192.168.100.8"
    web1.vm.provision "shell", path: "web1.sh"

  end

  
  config.vm.define "web2" do |web2|
    web2.vm.box = "bento/ubuntu-18.04"
    web2.vm.hostname = "web2"
    web2.vm.network :private_network, ip: "192.168.100.9"
    web2.vm.provision "shell", path: "web2.sh"

  end
end